/**
 * Pure renderer for the ER diagram (US6; FR-028).
 *
 * Produces a Mermaid `erDiagram` block wrapped in a fenced markdown
 * code block. Rendered by VS Code's built-in markdown preview — no
 * webview, no bundled grammar, no per-theme CSS. Mermaid is shipped
 * with VS Code's markdown preview pipeline.
 *
 * Trade-off recorded in research.md §7 (revised 2026-05-15): Mermaid's
 * layout engine breaks down past ~50 entities. We surface a friendly
 * warning at the configured threshold so users know to scope down
 * (e.g., view ER per-schema rather than per-database).
 *
 * Lives in its own file so unit tests can exercise the markdown
 * construction without a VS Code host.
 */

export interface ErColumn {
  name: string;
  type: string;
  isPk: boolean;
  notNull: boolean;
}

export interface ErTable {
  oid: number;
  schema: string;
  name: string;
  columns: ErColumn[];
}

export interface ErForeignKey {
  fromOid: number;
  toOid: number;
  fromColumns: string[];
  toColumns: string[];
  name: string;
}

export interface RenderOptions {
  /** Warn when total table count exceeds this. Default 50 (per Mermaid). */
  warnOverTables?: number;
}

/** Build a Mermaid erDiagram fenced in a markdown code block. */
export function buildMermaidErDiagram(
  tables: ReadonlyArray<ErTable>,
  foreignKeys: ReadonlyArray<ErForeignKey>,
  opts: RenderOptions = {},
): string {
  const warnAt = opts.warnOverTables ?? 50;
  const footer = ["", "<!-- Generated by cnpg4vscode · do not edit by hand -->"];

  if (tables.length === 0) {
    return ["_No tables in scope — nothing to diagram._", ...footer].join("\n");
  }

  const preamble: string[] = [];
  if (tables.length > warnAt) {
    preamble.push(
      `> ⚠️  **${tables.length} tables** exceed Mermaid's comfortable ER-diagram range (${warnAt}). Layout may be slow or unreadable. Narrow the scope: invoke **CNPG: Show ER Diagram** on a single schema instead of the whole database.`,
      "",
    );
  }

  // Sort everything for deterministic output (snapshot-friendly).
  const sortedTables = [...tables].sort((a, b) =>
    `${a.schema}.${a.name}`.localeCompare(`${b.schema}.${b.name}`),
  );
  const fkByOid = new Map<number, ErTable>();
  for (const t of sortedTables) fkByOid.set(t.oid, t);

  const lines: string[] = [];
  if (preamble.length > 0) lines.push(...preamble);
  lines.push("```mermaid");
  lines.push("erDiagram");

  for (const t of sortedTables) {
    const ident = sanitizeIdent(t.schema, t.name);
    if (t.columns.length === 0) {
      lines.push(`  ${ident} {`);
      lines.push(`    placeholder placeholder`);
      lines.push(`  }`);
      continue;
    }
    lines.push(`  ${ident} {`);
    for (const col of t.columns) {
      const type = sanitizeMermaidType(col.type);
      const colName = sanitizeColumnName(col.name);
      const flags = col.isPk ? " PK" : "";
      // Mermaid's erDiagram parser only accepts ATTRIBUTE_WORDs for the
      // type and name positions (alphanumeric + underscore). For PG types
      // like `timestamp with time zone`, `numeric(10,2)`, or `text[]`, we
      // strip to an alphanumeric form for the type column and preserve
      // the original PG type as the Mermaid column comment (which IS
      // allowed to be a double-quoted string).
      const annotation = type !== col.type ? ` "${escapeMermaidLabel(col.type)}"` : "";
      lines.push(`    ${type} ${colName}${flags}${annotation}`);
    }
    lines.push(`  }`);
  }

  // Foreign-key relationship lines. Use one-to-many (`||--o{`) by default;
  // we cannot reliably distinguish 1:1 vs 1:N from pg_constraint without
  // inspecting unique constraints on the FK columns. v1 keeps it simple.
  const sortedFks = [...foreignKeys].sort((a, b) =>
    `${a.fromOid}-${a.toOid}-${a.name}`.localeCompare(`${b.fromOid}-${b.toOid}-${b.name}`),
  );
  for (const fk of sortedFks) {
    const from = fkByOid.get(fk.fromOid);
    const to = fkByOid.get(fk.toOid);
    if (!from || !to) continue;
    const fromIdent = sanitizeIdent(from.schema, from.name);
    const toIdent = sanitizeIdent(to.schema, to.name);
    const label = fk.fromColumns.join(",");
    lines.push(`  ${toIdent} ||--o{ ${fromIdent} : "${escapeMermaidLabel(label)}"`);
  }

  lines.push("```");
  return [...lines, ...footer].join("\n");
}

/**
 * Join schema + name into a Mermaid-safe identifier.
 * Mermaid identifiers are letters/digits/underscore; leading digit is
 * disallowed; we also avoid characters that Mermaid's parser treats
 * specially.
 */
export function sanitizeIdent(schema: string, name: string): string {
  const raw = `${schema}_${name}`;
  const safe = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(safe) ? `_${safe}` : safe;
}

/**
 * Mermaid's erDiagram parser only accepts ATTRIBUTE_WORDs for the type
 * position (alphanumeric + underscore). Quoting multi-word types does
 * NOT work (despite my earlier assumption — quotes are reserved for the
 * column comment slot, not the type slot). For PG types we normalize:
 *   - drop parenthesized precision/modifiers: `numeric(10,2)` → `numeric`
 *   - convert `[]` to an `_array` suffix:     `text[]`       → `text_array`
 *   - collapse other non-word chars to `_`:    `double precision` → `double_precision`
 *   - leading digit gets an underscore prefix
 *   - empty result falls back to `unknown`
 *
 * The original PG type is preserved as a Mermaid column comment (caller
 * appends `"<original>"` when the normalized form differs).
 */
export function sanitizeMermaidType(type: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(type)) return type;
  let safe = type
    .replace(/\(.*?\)/g, "") // drop precision / modifiers
    .replace(/\[\s*\]/g, "_array") // arrays
    .replace(/[^A-Za-z0-9_]+/g, "_") // anything else → _
    .replace(/_+/g, "_") // collapse
    .replace(/^_+|_+$/g, ""); // trim
  if (safe.length === 0) safe = "unknown";
  if (/^[0-9]/.test(safe)) safe = `_${safe}`;
  return safe;
}

/**
 * Same rule for column names. PG identifiers usually pass through
 * untouched (alphanumeric + underscore) but a column quoted as
 * `"some name"` in SQL has the literal `some name` in `attname`.
 */
export function sanitizeColumnName(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
  let safe = name
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (safe.length === 0) safe = "column";
  if (/^[0-9]/.test(safe)) safe = `_${safe}`;
  return safe;
}

function escapeMermaidLabel(s: string): string {
  return s.replace(/"/g, "'");
}
